app = "kdd-rjz-ui"
primary_region = "fra"

[env]
  VITE_RACE_COMMAND_CENTER_URL = "https://kdd-rjz-race.fly.dev"
  VITE_ENABLE_RACE_COMMAND_CENTER_PREVIEW = "true"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
