import { useState } from 'react';
import { CheckCircle, AlertTriangle, XCircle, Wrench, CalendarCheck, Cloud, CloudOff, Trash2, RefreshCw } from 'lucide-react';
import { useToast } from '../components/ToastProvider';
import { PartGeneratorPanel } from '../components/PartGeneratorPanel';
import { usePartStorage } from '../hooks/usePartStorage';

const MAT_COLOR: Record<string, string> = {
  carbon:    '#38BDF8',
  aluminium: '#93C5FD',
  titanium:  '#A78BFA',
};

// ── Part definitions ──────────────────────────────────────────────────────────

interface Part {
  name: string;
  component: string;
  km: number;
  maxKm: number;
  status: 'ok' | 'warn' | 'crit';
  mass: number;
  fea: number | null;
  note: string;
}

const INITIAL_PARTS: Part[] = [
  { name: 'Front Fork Assembly',     component: 'Öhlins TTX25',     km: 1240, maxKm: 2000, status: 'ok',   mass: 4.2,  fea: null, note: '62% life remaining' },
  { name: 'Rear Shock',              component: 'Öhlins TTX36',     km: 1240, maxKm: 1800, status: 'warn', mass: 2.8,  fea: null, note: 'Schedule service next round' },
  { name: 'Carbon Front Rim',        component: 'Marchesini Ultra', km: 580,  maxKm: 3000, status: 'ok',   mass: 1.4,  fea: 107,  note: 'SIMP-optimized · –18% mass' },
  { name: 'Carbon Rear Rim',         component: 'Marchesini Ultra', km: 580,  maxKm: 3000, status: 'ok',   mass: 2.1,  fea: 142,  note: 'SIMP-optimized · –15% mass' },
  { name: 'Brake Discs (Front)',     component: 'Brembo GP-Style',  km: 980,  maxKm: 1200, status: 'warn', mass: 0.9,  fea: null, note: 'High wear — monitor' },
  { name: 'Brake Pads (Front)',      component: 'Brembo RC19',      km: 980,  maxKm: 1000, status: 'crit', mass: 0.15, fea: null, note: 'Replace before next session' },
  { name: 'Swingarm',                component: 'Alu-Ti Hybrid',    km: 8400, maxKm: 20000,status: 'ok',   mass: 3.8,  fea: 89,   note: 'Topology optimized · –22% mass' },
  { name: 'Front Upper Fairing',     component: 'Carbon Prototype', km: 2100, maxKm: 10000,status: 'ok',   mass: 1.2,  fea: 62,   note: 'Aero variant B3 active' },
  { name: 'Engine #4',               component: 'Prototype V4',     km: 2580, maxKm: 3500, status: 'ok',   mass: 62.0, fea: null, note: 'Within rev limit · Map 6' },
];

const DESIGN_VARIANTS = [
  { part: 'Carbon Front Rim', variant: 'V3 Baseline',  mass: 1.68, stress: 118, status: 'Archive' },
  { part: 'Carbon Front Rim', variant: 'V4 SIMP-INT4', mass: 1.40, stress: 107, status: 'Active' },
  { part: 'Carbon Front Rim', variant: 'V5 Prototype', mass: 1.31, stress: 122, status: 'Testing' },
  { part: 'Swingarm',         variant: 'Al Baseline',  mass: 4.90, stress: 145, status: 'Archive' },
  { part: 'Swingarm',         variant: 'Al-Ti V2',     mass: 4.20, stress: 132, status: 'Archive' },
  { part: 'Swingarm',         variant: 'Al-Ti V3+SIMP',mass: 3.80, stress: 89,  status: 'Active' },
];

// ── Status icon ───────────────────────────────────────────────────────────────

function StatusIcon({ status }: { status: string }) {
  if (status === 'ok')       return <CheckCircle   size={16} style={{ color: 'var(--green)' }} />;
  if (status === 'warn')     return <AlertTriangle size={16} style={{ color: 'var(--yellow)' }} />;
  if (status === 'scheduled')return <CalendarCheck size={16} style={{ color: 'var(--blue)' }} />;
  return <XCircle size={16} style={{ color: 'var(--accent)' }} />;
}

// ── Page ───────────────────────────────────────────────────────────────────────

export function PartDesignPage() {
  const { toast } = useToast();
  const [parts, setParts] = useState<Part[]>(INITIAL_PARTS);
  const [scheduledServices, setScheduledServices] = useState<Set<string>>(new Set());
  const { savedParts, loading: cloudLoading, refresh: cloudRefresh, remove: cloudRemove } = usePartStorage();

  // Derived stats
  const critParts  = parts.filter(p => p.status === 'crit' && !scheduledServices.has(p.name)).length;
  const warnParts  = parts.filter(p => p.status === 'warn' && !scheduledServices.has(p.name)).length;
  const okParts    = parts.filter(p => p.status === 'ok').length + scheduledServices.size;
  const totalMass  = parts.reduce((a, p) => a + p.mass, 0).toFixed(1);

  function addGeneratedPart(name: string, material: string, mass: number, stress: number) {
    const maxKm = material === 'carbon' ? 8000 : material === 'titanium' ? 15000 : 5000;
    setParts(prev => [
      ...prev,
      {
        name,
        component: `AI-Gen · ${material.charAt(0).toUpperCase() + material.slice(1)}`,
        km: 0,
        maxKm,
        status: 'ok',
        mass,
        fea: stress,
        note: `Generated by AI Part Generator · σ${stress} MPa`,
      },
    ]);
  }

  function scheduleService(part: Part) {
    setScheduledServices(prev => {
      const next = new Set(prev);
      next.add(part.name);
      return next;
    });
    // Update part status to 'warn' (from 'crit') to reflect it's been acknowledged
    setParts(prev => prev.map(p =>
      p.name === part.name && p.status === 'crit'
        ? { ...p, status: 'warn', note: `Service scheduled · ${new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}` }
        : p
    ));
    toast({
      type: 'success',
      title: `Service scheduled: ${part.name}`,
      message: `${part.component} — replacement before next session confirmed.`,
    });
  }

  function getDisplayStatus(part: Part): string {
    if (scheduledServices.has(part.name)) return 'scheduled';
    return part.status;
  }

  return (
    <div className="page">

      {/* ── AI Part Generator ────────────────────────────────────────────── */}
      <PartGeneratorPanel onAddPart={addGeneratedPart} />

      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="page-title">Part Design</h1>
          <p className="page-subtitle">Component lifecycle · FEA results · SIMP optimization · Design variants</p>
        </div>
        <div className="flex items-center gap-2">
          {critParts > 0 && <span className="badge badge-red">{critParts} Critical</span>}
          {warnParts > 0 && <span className="badge badge-yellow">{warnParts} Warning</span>}
          {scheduledServices.size > 0 && <span className="badge badge-blue">{scheduledServices.size} Scheduled</span>}
          <span className="badge badge-green">{okParts} Nominal</span>
        </div>
      </div>

      {/* ── Summary tiles ─────────────────────────────────────────────────── */}
      <div className="grid-4 mb-4">
        <div className="stat-tile accent-border">
          <div className="stat-tile__label">Critical Parts</div>
          <div className="stat-tile__value" style={{ color: critParts > 0 ? 'var(--accent)' : 'var(--text-muted)' }}>
            {critParts}
          </div>
          <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 4 }}>
            {critParts === 0 ? 'All acknowledged' : 'Requires attention'}
          </div>
        </div>
        <div className="stat-tile yellow-border">
          <div className="stat-tile__label">Warning Parts</div>
          <div className="stat-tile__value" style={{ color: 'var(--yellow)' }}>{warnParts}</div>
          <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 4 }}>Monitor closely</div>
        </div>
        <div className="stat-tile blue-border">
          <div className="stat-tile__label">Monitored Components</div>
          <div className="stat-tile__value">{parts.length}</div>
          {scheduledServices.size > 0 && (
            <div style={{ fontSize: 12, color: 'var(--blue)', marginTop: 4 }}>{scheduledServices.size} services queued</div>
          )}
        </div>
        <div className="stat-tile green-border">
          <div className="stat-tile__label">Total Component Mass</div>
          <div className="stat-tile__value text-mono">{totalMass}<span className="stat-tile__unit">kg</span></div>
          <div style={{ fontSize: 12, color: 'var(--green)', marginTop: 4 }}>–4.8 kg vs baseline</div>
        </div>
      </div>

      {/* ── Parts table ───────────────────────────────────────────────────── */}
      <div className="card mb-4">
        <div className="card-header">
          <span className="card-title flex items-center gap-2"><Wrench size={14} />Component Lifecycle</span>
        </div>
        <table className="data-table">
          <thead>
            <tr>
              <th>Status</th>
              <th>Part</th>
              <th>Component</th>
              <th>km Used</th>
              <th>Life %</th>
              <th>Mass (kg)</th>
              <th>FEA MPa</th>
              <th>Notes</th>
              <th style={{ width: 120 }}>Action</th>
            </tr>
          </thead>
          <tbody>
            {parts.map(p => {
              const lifePct = Math.round((p.km / p.maxKm) * 100);
              const displayStatus = getDisplayStatus(p);
              const isScheduled = scheduledServices.has(p.name);

              return (
                <tr
                  key={p.name}
                  style={
                    p.status === 'crit' && !isScheduled
                      ? { background: 'rgba(224,55,55,0.06)' }
                      : isScheduled
                      ? { background: 'rgba(59,130,246,0.06)' }
                      : {}
                  }
                >
                  <td><StatusIcon status={displayStatus} /></td>
                  <td style={{ fontWeight: 600 }}>{p.name}</td>
                  <td className="text-dim" style={{ fontSize: 12 }}>{p.component}</td>
                  <td className="mono">{p.km.toLocaleString()}</td>
                  <td>
                    <div className="flex items-center gap-2">
                      <div className="bar-track" style={{ width: 60 }}>
                        <div
                          className="bar-fill"
                          style={{
                            width: `${lifePct}%`,
                            background:
                              isScheduled ? 'var(--blue)' :
                              lifePct > 85 ? 'var(--accent)' :
                              lifePct > 65 ? 'var(--yellow)' : 'var(--green)',
                          }}
                        />
                      </div>
                      <span className="mono" style={{ fontSize: 12 }}>{lifePct}%</span>
                    </div>
                  </td>
                  <td className="mono">{p.mass}</td>
                  <td className="mono">{p.fea ?? '—'}</td>
                  <td style={{
                    fontSize: 12,
                    color: isScheduled ? 'var(--blue)' : p.status === 'crit' ? 'var(--accent)' : p.status === 'warn' ? 'var(--yellow)' : 'var(--text-dim)',
                  }}>
                    {p.note}
                  </td>
                  <td>
                    {(p.status === 'crit' || p.status === 'warn') && !isScheduled ? (
                      <button
                        className="btn btn-ghost btn-sm flex items-center gap-1"
                        style={{
                          fontSize: 11,
                          padding: '4px 8px',
                          color: p.status === 'crit' ? 'var(--accent)' : 'var(--yellow)',
                          borderColor: p.status === 'crit' ? 'rgba(224,55,55,0.3)' : 'rgba(245,158,11,0.3)',
                        }}
                        onClick={() => scheduleService(p)}
                      >
                        <CalendarCheck size={12} />
                        Schedule
                      </button>
                    ) : isScheduled ? (
                      <span style={{ fontSize: 11, color: 'var(--blue)', fontWeight: 600 }}>✓ Scheduled</span>
                    ) : (
                      <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>—</span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ── Cloud Inventory (InsForge) ───────────────────────────────────── */}
      <div className="card mb-4">
        <div className="card-header">
          <div className="flex items-center gap-2">
            <Cloud size={14} style={{ color: '#38BDF8' }} />
            <span className="card-title">Cloud Inventory</span>
            <span style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'JetBrains Mono,monospace' }}>
              InsForge · PostgreSQL + Storage
            </span>
          </div>
          <div className="flex items-center gap-2">
            <span style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'JetBrains Mono,monospace' }}>
              {savedParts.length} part{savedParts.length !== 1 ? 's' : ''}
            </span>
            <button
              onClick={() => cloudRefresh()}
              style={{
                display: 'flex', alignItems: 'center', gap: 5,
                padding: '4px 10px',
                background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.1)',
                borderRadius: 5, cursor: 'pointer', color: 'var(--text-muted)',
                fontSize: 11, fontFamily: 'JetBrains Mono,monospace',
              }}
            >
              <RefreshCw size={11} style={{ animation: cloudLoading ? 'spin 1s linear infinite' : 'none' }} />
              Sync
            </button>
          </div>
        </div>

        {cloudLoading && savedParts.length === 0 ? (
          <div style={{ padding: '24px 16px', textAlign: 'center', color: 'var(--text-muted)', fontSize: 12, fontFamily: 'JetBrains Mono,monospace' }}>
            <Wrench size={14} style={{ marginRight: 6, opacity: 0.4 }} />
            Syncing with InsForge...
          </div>
        ) : savedParts.length === 0 ? (
          <div style={{ padding: '24px 16px', textAlign: 'center', color: 'var(--text-muted)', fontSize: 12, fontFamily: 'JetBrains Mono,monospace' }}>
            <CloudOff size={14} style={{ marginRight: 6, opacity: 0.4 }} />
            No AI-generated parts saved yet. Use the generator above and click "Save to InsForge".
          </div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Part ID</th>
                <th>Material</th>
                <th>Dimensions</th>
                <th>Mass</th>
                <th>Peak σ</th>
                <th>SF</th>
                <th>Drag Cd</th>
                <th>Prompt</th>
                <th>Saved</th>
                <th>Sync</th>
                <th style={{ width: 40 }}></th>
              </tr>
            </thead>
            <tbody>
              {savedParts.map(p => (
                <tr key={p.part_id}>
                  <td className="mono" style={{ fontSize: 10, color: 'var(--text-muted)' }}>
                    {p.part_id.slice(-10)}
                  </td>
                  <td>
                    <span style={{
                      fontSize: 11, fontWeight: 700,
                      color: MAT_COLOR[p.material] ?? 'var(--text)',
                      fontFamily: 'JetBrains Mono,monospace',
                    }}>
                      {p.material.charAt(0).toUpperCase() + p.material.slice(1)}
                    </span>
                  </td>
                  <td className="mono" style={{ fontSize: 11 }}>
                    {p.dim_x}×{p.dim_y}×{p.dim_z}mm
                  </td>
                  <td className="mono" style={{ color: MAT_COLOR[p.material] }}>{p.mass_kg} kg</td>
                  <td className="mono"
                    style={{ color: p.peak_stress > 250 ? 'var(--yellow)' : 'var(--text)' }}>
                    {p.peak_stress} MPa
                  </td>
                  <td className="mono"
                    style={{ color: p.safety_factor >= 2.0 ? 'var(--green)' : 'var(--yellow)', fontWeight: 700 }}>
                    {p.safety_factor.toFixed(2)}
                  </td>
                  <td className="mono" style={{ fontSize: 11 }}>{p.drag_coeff}</td>
                  <td style={{ fontSize: 11, color: 'var(--text-muted)', maxWidth: 160, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {p.prompt || '—'}
                  </td>
                  <td style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'JetBrains Mono,monospace' }}>
                    {p.created_at ? new Date(p.created_at).toLocaleString('en-GB', { day:'2-digit', month:'short', hour:'2-digit', minute:'2-digit' }) : '—'}
                  </td>
                  <td>
                    {p.synced_to_cloud
                      ? <span style={{ fontSize: 10, color: '#22C55E', fontFamily: 'JetBrains Mono,monospace' }}>☁ Cloud</span>
                      : <span style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'JetBrains Mono,monospace' }}>💾 Local</span>
                    }
                  </td>
                  <td>
                    <button
                      onClick={() => {
                        cloudRemove(p.part_id);
                        toast({ type: 'info', title: 'Removed from local list', message: p.name });
                      }}
                      style={{
                        background: 'none', border: 'none', cursor: 'pointer',
                        color: 'var(--text-muted)', padding: 4,
                      }}
                    >
                      <Trash2 size={12} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* ── Design variants comparison ───────────────────────────────────── */}
      <div className="card">
        <div className="card-header">
          <span className="card-title">Design Variant Comparison — SIMP Optimization Results</span>
        </div>
        <table className="data-table">
          <thead>
            <tr><th>Part</th><th>Variant</th><th>Mass (kg)</th><th>Peak Stress (MPa)</th><th>Safety Factor</th><th>Status</th></tr>
          </thead>
          <tbody>
            {DESIGN_VARIANTS.map((v, i) => {
              const sf = (250 / v.stress).toFixed(2);
              return (
                <tr key={i} style={v.status === 'Active' ? { background: 'var(--green-dim)' } : {}}>
                  <td style={{ fontWeight: 600 }}>{v.part}</td>
                  <td>{v.variant}</td>
                  <td className="mono">{v.mass}</td>
                  <td className="mono" style={{ color: v.stress > 140 ? 'var(--yellow)' : 'var(--text)' }}>{v.stress}</td>
                  <td className="mono" style={{ color: parseFloat(sf) > 2 ? 'var(--green)' : 'var(--yellow)' }}>{sf}</td>
                  <td>
                    <span className={`badge ${v.status === 'Active' ? 'badge-green' : v.status === 'Testing' ? 'badge-blue' : 'badge-muted'}`}>
                      {v.status}
                    </span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
